In [16]:
import numpy as np
import matplotlib.pyplot as plt

In [17]:
def derivative(x1,x2):
    f1 = 2*(x1-4) + 10*np.cos(x1)*np.sin(x2)
    f2 = 2*(x2-3) + 10*np.sin(x1)*np.cos(x2)
    return np.array([f1,f2])

In [18]:
def hessian(x1,x2):
    d2x1 = 2 - 10*np.sin(x1)*np.sin(x2)
    d2x2 = 2 - 10*np.sin(x1)*np.sin(x2)
    d2x1x2 = 10*np.cos(x1)*np.cos(x2)
    d2x2x1 = 10*np.cos(x2)*np.cos(x1)
    return np.matrix([[d2x1,d2x1x2],[d2x2x1,d2x2]])

In [19]:
def func_value(x1,x2):
    f = np.power((x1-4),2) + np.power((x2-3),2) + 10*np.sin(x1)*np.sin(x2) + 5
    return f

In [20]:
def check_convergence(X,Y):
    X11 = np.linalg.norm(Y - X)
    F11 = np.linalg.norm(func_value(Y[0],Y[1]) - func_value(X[0],X[1]))
    return X11,F11

Initial Guess

In [25]:
X1 = np.array([2,4])
F = func_value(X1[0],X1[1])
DF = derivative(X1[0],X1[1])
H = hessian(X1[0],X1[1])
H_inv = np.linalg.inv(H)
X2 = X1 - np.dot(H_inv,DF)
X2.flatten()

matrix([[1.955621  , 4.45760756]])

In [38]:
itr = 0
epsilon = 0.000001
while (True):
    if(itr == 0):
        X = np.array([2,4])
    else:
        X = Y
    F = func_value(X[0],X[1])
    DF = derivative(X[0],X[1])
    H = hessian(X[0],X[1])
    H_inv = np.linalg.inv(H)
    Y = X - np.dot(H_inv,DF)
    Y = np.squeeze(np.asarray(Y))
    itr += 1
    print("Itr: ",itr)
    print("Function Value: ",F)
    print("Derivative: ",DF)
    print("Hessian Inverse: \n",H_inv)
    print("Initail: ",X)
    print("Final: ",Y)
    print()
    print()
    if(check_convergence(X,Y)[0] < epsilon and check_convergence(X,Y)[1] < epsilon):
        break

Itr:  1
Function Value:  3.118414384012458
Derivative:  [-0.85059036 -3.94356463]
Hessian Inverse: 
 [[ 0.12424661 -0.03805237]
 [-0.03805237  0.12424661]]
Initail:  [2 4]
Final:  [1.955621   4.45760756]


Itr:  2
Function Value:  2.3346691886872595
Derivative:  [-0.45597559  0.57920302]
Hessian Inverse: 
 [[ 0.09184565 -0.0079218 ]
 [-0.0079218   0.09184565]]
Initail:  [1.955621   4.45760756]
Final:  [2.00208871 4.40079813]


Itr:  3
Function Value:  2.307056502748039
Derivative:  [-0.01667178  0.01660426]
Hessian Inverse: 
 [[ 0.09530568 -0.01147245]
 [-0.01147245  0.09530568]]
Initail:  [2.00208871 4.40079813]
Final:  [2.00386811 4.39902438]


Itr:  4
Function Value:  2.307026918613383
Derivative:  [-2.13766817e-05  2.13766626e-05]
Hessian Inverse: 
 [[ 0.09544334 -0.01161005]
 [-0.01161005  0.09544334]]
Initail:  [2.00386811 4.39902438]
Final:  [2.0038704 4.3990221]


Itr:  5
Function Value:  2.3070269185644623
Derivative:  [-3.55631080e-11  3.55613317e-11]
Hessian Inverse: 
 [[ 0.